---
abstract: 'Redis backend for Dancer Session Engine'
author:
  - 'Anton Gerasimov <chim@cpan.org>'
build_requires:
  Test::More: 0.98
  Test::Pod: 1.22
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-Redis
no_index:
  directory:
    - t
    - xt
    - eg
    - examples
    - corpus
  namespace:
    - t::lib
  package:
    - DB
provides:
  Dancer::Session::Redis:
    file: lib/Dancer/Session/Redis.pm
    version: 0.21
requires:
  Carp: 1.26
  Dancer: 1.3072
  Redis: 1.955
  Storable: 2.27
  feature: 0
  parent: 0
  perl: 5.010001
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/Wu-Wu/Dancer-Session-Redis/issues
  homepage: https://metacpan.org/release/Dancer-Session-Redis
  repository: git://github.com/Wu-Wu/Dancer-Session-Redis.git
version: 0.21
x_authority: cpan:CHIM
