---
abstract: 'Redis backend for Dancer Session Engine'
author:
  - 'Anton Gerasimov <me@zyxmasta.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Session-Redis
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Dancer: 1.3072
  Redis: 0
  Storable: 0
  parent: 0
  perl: 5.010000
  strict: 0
  warnings: 0
version: v0.1.8
